/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminInternalPage;

import StudentsInternalPage.viewApplicants;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import scholarPage.selectScholar;
import adminMain.adminDashBoard;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class adminDashPage extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form dashBoardPage
     */
    public adminDashPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    Color navcolor=new Color(255,66,66);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(255,255,204);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    Color dgreencolor=new Color(27,102,102);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dshBody = new javax.swing.JPanel();
        backArrow = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        manApply = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        viewApplicants = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        manSettings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        dshBody.setBackground(new java.awt.Color(255, 255, 204));
        dshBody.setForeground(new java.awt.Color(204, 204, 204));
        dshBody.setPreferredSize(new java.awt.Dimension(750, 439));
        dshBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backArrow.setBackground(new java.awt.Color(255, 255, 204));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrowMouseExited(evt);
            }
        });
        backArrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        dshBody.add(backArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel9.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel9.setText("SCHOLARSHIP TRACKING APP");
        dshBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 360, 40));

        jLabel10.setText("A TRACKING SYSTEM TO MANAGE STUDENT SCHOLARHIP APPLICATION");
        dshBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 420, 20));

        jPanel1.setBackground(new java.awt.Color(0, 43, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 120));

        dshBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 180, 180));

        jPanel2.setBackground(new java.awt.Color(255, 66, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manApply.setBackground(new java.awt.Color(255, 255, 204));
        manApply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manApplyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manApplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manApplyMouseExited(evt);
            }
        });
        manApply.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGE APPLICANTS");
        manApply.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-manage-94.png"))); // NOI18N
        manApply.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 130));

        jPanel2.add(manApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 170, 150));

        viewApplicants.setBackground(new java.awt.Color(255, 255, 204));
        viewApplicants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewApplicantsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewApplicantsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewApplicantsMouseExited(evt);
            }
        });
        viewApplicants.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VIEW APPLICANTS");
        viewApplicants.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-94.png"))); // NOI18N
        viewApplicants.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 90));

        jPanel2.add(viewApplicants, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 170, 150));

        manSettings.setBackground(new java.awt.Color(255, 255, 204));
        manSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        manSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manSettingsMouseExited(evt);
            }
        });
        manSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HELP");
        manSettings.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-service-94.png"))); // NOI18N
        manSettings.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        jPanel2.add(manSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 170, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dshBody, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dshBody, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backArrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseEntered
       backArrow.setBackground(lightcolor);
    }//GEN-LAST:event_backArrowMouseEntered

    private void backArrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseExited
       backArrow.setBackground(backcolor);  
    }//GEN-LAST:event_backArrowMouseExited

    private void backArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseClicked
       this.toBack();
        adminDashBoard apd= new adminDashBoard();
        setVisible(false);
        new adminDashBoard().toFront();
        new adminDashBoard().setState(java.awt.Frame.NORMAL);
        apd.toFront();

    }//GEN-LAST:event_backArrowMouseClicked

    private void manApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manApplyMouseClicked
       selectScholar ss=new selectScholar();
       ss.setVisible(true);
       //this.dispose();
    }//GEN-LAST:event_manApplyMouseClicked

    private void manApplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manApplyMouseEntered
        manApply.setBackground(lightcolor);
    }//GEN-LAST:event_manApplyMouseEntered

    private void manApplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manApplyMouseExited
      manApply.setBackground(bodycolor);
    }//GEN-LAST:event_manApplyMouseExited

    private void viewApplicantsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewApplicantsMouseEntered
         viewApplicants.setBackground(lightcolor);
    }//GEN-LAST:event_viewApplicantsMouseEntered

    private void viewApplicantsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewApplicantsMouseExited
        viewApplicants.setBackground(bodycolor);
    }//GEN-LAST:event_viewApplicantsMouseExited

    private void manSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manSettingsMouseEntered
        manSettings.setBackground(lightcolor);
    }//GEN-LAST:event_manSettingsMouseEntered

    private void manSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manSettingsMouseExited
        manSettings.setBackground(bodycolor);
    }//GEN-LAST:event_manSettingsMouseExited

    private void viewApplicantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewApplicantsMouseClicked
     
         JFrame mainFrame=(JFrame)SwingUtilities.getWindowAncestor(this);
         mainFrame.setVisible(true);
        viewApplicants va=new viewApplicants();
        va.setVisible(true);
    }//GEN-LAST:event_viewApplicantsMouseClicked
int x=200;    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backArrow;
    private javax.swing.JPanel dshBody;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel manApply;
    private javax.swing.JPanel manSettings;
    private javax.swing.JPanel viewApplicants;
    // End of variables declaration//GEN-END:variables
}
