/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginForm;

import static LoginForm.Register1.jTextField1;
import static LoginForm.Register1.jTextField2;
import static LoginForm.Register1.jTextField3;
import static LoginForm.Register1.jTextField4;
import static LoginForm.Register1.jTextField5;
import static LoginForm.Register1.jTextField6;
import static LoginForm.Register1.jTextField7;

import adminMain.mainDashboard;
/*
import static adminMain.Admin.Bdate;
import static adminMain.Admin.FName;
import static adminMain.Admin.LName;
import static adminMain.Admin.MName;
import static adminMain.Admin.archieveData;
import static adminMain.Admin.brgy;
import static adminMain.Admin.city;
import static adminMain.Admin.email;
import static adminMain.Admin.gender;
import static adminMain.Admin.jTable5;
import static adminMain.Admin.number;
import static adminMain.Admin.postal;
import static adminMain.Admin.province;
import static adminMain.Admin.purok;
import javax.swing.table.DefaultTableModel;
*/
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInFormBeroy
     */
    public LoginForm() {
        initComponents();
             jLabel4.setVisible(false);
            username.setVisible(false);
            password.setVisible(false);
            login.setVisible(false);          
    }
    Color logcolor=new Color(51,51,255);
    Color navcolor=new Color(255,66,66);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(102,102,102);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    Color logincolor=new Color(0,43,50);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setUndecorated(true);

        jPanel2.setLayout(null);

        header.setBackground(new java.awt.Color(255, 66, 66));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(255, 66, 66));
        minimize.setForeground(new java.awt.Color(255, 51, 51));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-subtract-26.png"))); // NOI18N
        minimize.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 40));

        close.setBackground(new java.awt.Color(255, 66, 66));
        close.setForeground(new java.awt.Color(255, 0, 0));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-close-26.png"))); // NOI18N
        close.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 40));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(15, 13, 13));
        jLabel12.setText("ScholarshipTracker- St.Cecilia's College-Cebu Inc. ");
        header.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 20));

        jPanel2.add(header);
        header.setBounds(0, 0, 800, 40);

        jPanel3.setBackground(new java.awt.Color(0, 43, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/allevo-removebg-preview (2).png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 390, 260));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/unifast-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 250, 220));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/cheds-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, 210));

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 40, 380, 400);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBackground(new java.awt.Color(255, 255, 204));
        username.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), null), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 340, 60));

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), null), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18))); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, 70));

        login.setBackground(new java.awt.Color(0, 43, 50));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/cheek.png"))); // NOI18N
        jLabel2.setText("LOGIN");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 130, -1));

        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 340, 40));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel4.setText("PS: Write your id no. if you're a student");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 200, -1));

        jCombo.setBackground(new java.awt.Color(255, 0, 0));
        jCombo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login As", "Applicant", "Administrator" }));
        jCombo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });
        jPanel1.add(jCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, 50));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setText("Select Role:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 232, 340, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel13.setText("New user? Create Account !");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, 30));

        jPanel2.add(jPanel1);
        jPanel1.setBounds(380, 0, 420, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(800, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(headcolor);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(logincolor);
    }//GEN-LAST:event_loginMouseExited

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
 
        /* String f= FName.getText();
            String l= LName.getText();
            String m= MName.getText();
            String b= Bdate.getText();
            String n= number.getText();
            String e= email.getText();
            String by= brgy.getText();
            String pk= purok.getText();
            String cy= city.getText();
            String prov= province.getText();
            String pl= postal.getText();
            String gr= gender.getText();
        */
/*        String an=jTextField2.getText();
         String ps=jTextField3.getText();
         String fn=jTextField4.getText();
          String ln=jTextField5.getText();
         String bd=jTextField6.getText();
          String pe=jTextField7.getText();
           String cn=jTextField1.getText();*/
        
       String user= username.getText();
        String pass= password.getText();
      if(jCombo.getSelectedIndex()==1){
             
         if(username.getText().isEmpty()|| password.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Please Fill up other fields.","Message",JOptionPane.WARNING_MESSAGE);
       }else if(user.equals("SCC-19-0009694")&&pass.equals("10-03-2002")){
        JOptionPane.showMessageDialog(null,"SUCCESS!");
         mainDashboard ad = new mainDashboard();

            mainDashboard.acc_Username.setText(username.getText());
          mainDashboard.acc_Pass.setText(password.getText());
           mainDashboard.userName.setText(username.getText()); 
          // Admin.submit.setVisible(false);
          
         //  Admin.viewStatus.setVisible(false);
            mainDashboard.viewApplicants.setVisible(false);
             mainDashboard.manageApply.setVisible(false);
            mainDashboard.pendings.setVisible(false);
         mainDashboard.delete1.setVisible(false);
          mainDashboard.archieveData.setVisible(false);
          mainDashboard.viewApplicants.setVisible(false);
           mainDashboard.pendings.setVisible(false);
         
           ad.setVisible(true);
            this.dispose();
       }
       /*  else if(user.equals(an)&&pass.equals(ps)){
        JOptionPane.showMessageDialog(null,"SUCCESS!");
          
        Admin us = new Admin();
        us.setVisible(true); 
           // Admin.accountName.setText(username.getText());
        //  Admin.accountPass.setText(password.getText());
         //  Admin.userName.setText(username.getText()); 
          // Admin.submit.setVisible(false);
        
          Admin.fName.setText(jTextField4.getText());
         Admin.lName.setText(jTextField5.getText());
         Admin.bDate.setText(jTextField6.getText());
         Admin.pEmail.setText(jTextField7.getText());*
          Admin.contactNum.setText(jTextField1.getText());*/
        /*   String data[]={FName.getText(),LName.getText(),MName.getText(),
                    Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                    purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
                DefaultTableModel tbl= (DefaultTableModel)jTable5.getModel();
                tbl.addRow(data);
             */
   /*     Admin.manageApply.setVisible(false);
        Admin.userName.setText(username.getText()); 
        Admin.accountName.setText(username.getText());
          Admin.accountPass.setText(password.getText());
           Admin.viewApplicants.setVisible(false);
            Admin.pendings.setVisible(false);
         Admin.delete1.setVisible(false);
          Admin.archieveData.setVisible(false);
          Admin.viewApplicants.setVisible(false);
           Admin.pendings.setVisible(false);
        //Admin.nav_dashboard.setVisible(false);
        this.dispose();
         }*/
         else if(user.equals("SCC-19-0009696")&&pass.equals("10-03-2001")){
        JOptionPane.showMessageDialog(null,"SUCCESS!");
         mainDashboard ad = new mainDashboard();
        
            mainDashboard.acc_Username.setText(username.getText());
          mainDashboard.acc_Pass.setText(password.getText());
           mainDashboard.userName.setText(username.getText()); 
          // Admin.submit.setVisible(false);
           
           //Admin.viewStatus.setVisible(false);
           mainDashboard.viewApplicants.setVisible(false);
             mainDashboard.manageApply.setVisible(false);
            mainDashboard.pendings.setVisible(false);
         mainDashboard.delete1.setVisible(false);
          mainDashboard.archieveData.setVisible(false);
          mainDashboard.viewApplicants.setVisible(false);
           mainDashboard.pendings.setVisible(false);
           ad.setVisible(true);
            this.dispose();
       }
        /* else if(user.equals(an)&&pass.equals(ps)){
//else if(user.equals("SCC-19-0009696")&&pass.equals("10-03-2001")){
             Admin us = new Admin();
        us.setVisible(true); */
      /*  String data[]={FName.getText(),LName.getText(),MName.getText(),
                    Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                    purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
                DefaultTableModel tbl= (DefaultTableModel)jTable5.getModel();
                tbl.addRow(data);*/
       /*    Admin.fName.setText(jTextField4.getText());
         Admin.lName.setText(jTextField5.getText());
         Admin.bDate.setText(jTextField6.getText());
         Admin.pEmail.setText(jTextField7.getText());
          Admin.contactNum.setText(jTextField1.getText());
        Admin.manageApply.setVisible(false);
         Admin.accountName.setText(username.getText());
          Admin.accountPass.setText(password.getText());
        Admin.userName.setText(username.getText()); 
        Admin.archieveData.setVisible(false);
         Admin.delete1.setVisible(false);
          Admin.archieveData.setVisible(false);
          Admin.viewApplicants.setVisible(false);
           Admin.pendings.setVisible(false);
        //Admin.nav_dashboard.setVisible(false);
        this.dispose();
         }*/ else{
             JOptionPane.showMessageDialog(null,"Invalid Account.","Message",JOptionPane.WARNING_MESSAGE);
            /* if(an.equals("")||ps.equals("")||fn.equals("")||ln.equals("")
            ||bd.equals("")||pe.equals("")||cn.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter all the data!");

            }*/
            
        }
        }if(jCombo.getSelectedIndex()==2){
            if(username.getText().isEmpty()|| password.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Please Fill up all the fields.","Message",JOptionPane.WARNING_MESSAGE);
       }else if(user.equals("ADMIN1")&&pass.equals("PASSWORD1")){
        JOptionPane.showMessageDialog(null,"SUCCESS!");
         mainDashboard ad = new mainDashboard();
       
            mainDashboard.acc_Username.setText(username.getText());
          mainDashboard.acc_Pass.setText(password.getText());
           mainDashboard.userName.setText(username.getText()); 
          // Admin.submit.setVisible(false);
           
           mainDashboard.viewStatus.setVisible(false);
            mainDashboard.guide.setVisible(false);
            mainDashboard.nav_apply.setVisible(false);
            
           ad.setVisible(true);
             this.dispose();
       }
            /*else if(user.equals(an)&&pass.equals(ps) ){
            ///else if(user.equals("ADMIN1")&&pass.equals("PASSWORD1")){
        JOptionPane.showMessageDialog(null,"SUCCESS!");
            
            
            Admin ad = new Admin();*/
         /*   String data[]={FName.getText(),LName.getText(),MName.getText(),
                    Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                    purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
                DefaultTableModel tbl= (DefaultTableModel)jTable5.getModel();
                tbl.addRow(data);*/
          /*    Admin.fName.setText(jTextField4.getText());
         Admin.lName.setText(jTextField5.getText());
         Admin.bDate.setText(jTextField6.getText());
         Admin.pEmail.setText(jTextField7.getText());
          Admin.contactNum.setText(jTextField1.getText());
            Admin.accountName.setText(username.getText());
          Admin.accountPass.setText(password.getText());
           Admin.userName.setText(username.getText()); 
          // Admin.submit.setVisible(false);
           Admin.reset.setVisible(false);
           Admin.viewStatus.setVisible(false);
            Admin.nav_apply.setVisible(false);
           //Admin.jCombo2.setVisible(false);
          //   Admin.accName.setText(username.getText()); 
            ad.setVisible(true);
         this.dispose();
        } */else{
             JOptionPane.showMessageDialog(null,"Invalid Account.","Message",JOptionPane.WARNING_MESSAGE);
        /*   if(an.equals("")||ps.equals("")||fn.equals("")||ln.equals("")
            ||bd.equals("")||pe.equals("")||cn.equals("")){
             JOptionPane.showMessageDialog(null,"Please Fill up all the fields.","Message",JOptionPane.WARNING_MESSAGE);

            }*/
            
        }
        }
     
    }//GEN-LAST:event_loginMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
      int z=JOptionPane.showConfirmDialog(this, "are you sure do you want to exit this application?","NOTE",JOptionPane.YES_NO_OPTION);
       if(z==0){
      System.exit(0);
       }else{
       }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
           close.setBackground(closecolor);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
          close.setBackground(headcolor);
    }//GEN-LAST:event_closeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
      setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(mincolor);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
       minimize.setBackground(headcolor);
    }//GEN-LAST:event_minimizeMouseExited

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed
        // TODO add your handling code here:
      
            
        if(jCombo.getSelectedIndex()==1){
            jLabel4.setVisible(true);
            username.setVisible(true);
            password.setVisible(true);
            login.setVisible(true);
           
        }if(jCombo.getSelectedIndex()==2){
             jLabel4.setVisible(true);
            username.setVisible(true);
            password.setVisible(true);
            login.setVisible(true);
        }
           
    }//GEN-LAST:event_jComboActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
      
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
     Register1 rg=new Register1();
      rg.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
      Register1 rg=new Register1();
      rg.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
      
    }//GEN-LAST:event_jPanel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel close;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel login;
    private javax.swing.JPanel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    public boolean isClosed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
