/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginForm;

import adminMain.Admin;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Register1 extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register1() {
        initComponents();
        
    }
Color navcolor=new Color(255,66,66);
    Color logcolor=new Color(51,51,255);
    Color navecolor=new Color(0,43,50);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(102,102,102);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    Color logincolor=new Color(0,43,50);
     Color whitecolor=new Color(255,255,255);
    Color graycolor=new Color(51,51,51);
    Color dgreencolor=new Color(27,102,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backArrow = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        profile = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        accName = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jGender1 = new javax.swing.JComboBox<>();
        jSubmit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backArrow.setBackground(new java.awt.Color(204, 255, 204));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrowMouseExited(evt);
            }
        });
        backArrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setBackground(new java.awt.Color(0, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        backArrow.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        getContentPane().add(backArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-customer-100.png"))); // NOI18N
        profile.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 130));

        accName.setText("UPLOAD");
        profile.add(accName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, 30));

        jPanel5.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 160, 160));

        jLabel57.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel57.setText("ACCOUNT REGISTRATION");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 360, 40));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel58.setText("PERSONAL INFO:");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 20));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel60.setText("CREATE ACOUNT:");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        jLabel61.setText("USER NAME:");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 610, 10));

        jLabel62.setText("FIRST NAME:");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 30));

        jLabel64.setText("PASSWORD:");
        jPanel5.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        jLabel65.setText("LAST NAME:");
        jPanel5.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 30));

        jLabel66.setText("BIRTHDATE:");
        jPanel5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 80, 30));

        jLabel68.setText("EMAIL:");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, 30));

        jLabel69.setText("GENDER:");
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 30));

        jLabel70.setText("CONTACT NUMBER:");
        jPanel5.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 30));

        jGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE", "MALE", "FEMALE", " " }));
        jPanel5.add(jGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 422, 110, 30));

        jSubmit.setBackground(new java.awt.Color(9, 233, 255));
        jSubmit.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });
        jPanel5.add(jSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 300, 30));
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 300, 30));
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 300, 30));
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 300, 30));
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 300, 30));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 300, 30));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 300, 30));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        jPanel5.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 190, 120));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 530));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseClicked
       LoginForm main = new LoginForm();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backArrowMouseClicked

    private void backArrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseEntered
        backArrow.setBackground(lightcolor);
    }//GEN-LAST:event_backArrowMouseEntered

    private void backArrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseExited
        backArrow.setBackground(backcolor);
    }//GEN-LAST:event_backArrowMouseExited

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        String an=jTextField2.getText();
         String ps=jTextField3.getText();
         String fn=jTextField4.getText();
          String ln=jTextField5.getText();
         String bd=jTextField6.getText();
          String pe=jTextField7.getText();
           String cn=jTextField1.getText();
        
            if(an.equals("")||ps.equals("")||fn.equals("")||ln.equals("")
            ||bd.equals("")||pe.equals("")||cn.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter all the data!");

            }else {
                 JOptionPane.showMessageDialog(null,"SUCCESS!");
            
            
           //Admin ad = new Admin();
            LoginForm  lf = new LoginForm();
           // Admin.accountName.setText(username.getText());
        //  Admin.accountPass.setText(password.getText());
         //  Admin.userName.setText(username.getText()); 
          // Admin.submit.setVisible(false);
      /*    Admin.fName.setText(jTextField4.getText());
         Admin.lName.setText(jTextField4.getText());
         Admin.bDate.setText(jTextField5.getText());
         Admin.pEmail.setText(jTextField6.getText());
          Admin.contactNum.setText(jTextField7.getText());
           //Admin.jGender.setText(jTextField1.getText());*/
            
           lf.setVisible(true);
         this.dispose();
        }
            
    }//GEN-LAST:event_jSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accName;
    private javax.swing.JPanel backArrow;
    private javax.swing.JComboBox<String> jGender1;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton jSubmit;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel profile;
    // End of variables declaration//GEN-END:variables
}
