/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminMain;
import java.awt.Color;
import javax.swing.JOptionPane;
import adminInternalPage.adminSet;
import adminInternalPage.adminDashPage;
import StudentsInternalPage.studentPage;
import adminInternalPage.applicants;
/**
 *
 * @author Administrator
 */
public class adminDashBoard extends javax.swing.JFrame {
public String username;
    /**
     * Creates new form appDashBoard
     */
    public adminDashBoard() {
        initComponents();
        this.jMenuItem1.setText("WELCOME "+this.username);
    }
   Color navcolor=new Color(255,66,66);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(102,102,102);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        body = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nav_dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nav_account = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        nav_student1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        navdesign = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accName1 = new javax.swing.JLabel();
        accName2 = new javax.swing.JLabel();
        mainDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        body.setBackground(new java.awt.Color(255, 255, 204));
        body.setPreferredSize(new java.awt.Dimension(800, 420));
        body.setLayout(null);

        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        navbar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 120));

        nav_dashboard.setBackground(new java.awt.Color(255, 66, 66));
        nav_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_dashboardMouseExited(evt);
            }
        });
        nav_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DASH BOARD");
        nav_dashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 40));

        navbar.add(nav_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, -1));

        nav_account.setBackground(new java.awt.Color(255, 66, 66));
        nav_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_accountMouseExited(evt);
            }
        });
        nav_account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ACCOUNT");
        nav_account.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 40));

        navbar.add(nav_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/icons8-menu-rounded-50.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
        });
        navbar.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        nav_student1.setBackground(new java.awt.Color(0,43,80));
        nav_student1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_student1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_student1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_student1MouseExited(evt);
            }
        });
        nav_student1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADMIN");
        nav_student1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 90, 40));

        navbar.add(nav_student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 460));

        navdesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/vintageSCC-1000.jpg"))); // NOI18N
        navdesign.setPreferredSize(new java.awt.Dimension(100, 100));
        navbar.add(navdesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 460));

        body.add(navbar);
        navbar.setBounds(0, 40, 200, 460);

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        body.add(logo2);
        logo2.setBounds(0, 100, 200, 80);

        header.setBackground(new java.awt.Color(255, 66, 66));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(255, 66, 66));
        minimize.setForeground(new java.awt.Color(255, 51, 51));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-subtract-26.png"))); // NOI18N
        minimize.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 40, 40));

        close.setBackground(new java.awt.Color(255, 66, 66));
        close.setForeground(new java.awt.Color(255, 0, 0));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-close-26.png"))); // NOI18N
        close.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 50, 40));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 13, 13));
        jLabel3.setText("ScholarshipTracker- St.Cecilia's College-Cebu Inc. ");
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 20));

        accName1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        accName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.add(accName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 20));

        accName2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        accName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.add(accName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 160, 20));

        body.add(header);
        header.setBounds(0, 0, 980, 40);

        mainDesktop.setBackground(new java.awt.Color(255, 255, 204));
        mainDesktop.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground1.jpg"))); // NOI18N

        mainDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDesktopLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDesktopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        body.add(mainDesktop);
        mainDesktop.setBounds(200, 40, 780, 460);

        menu1.setBackground(new java.awt.Color(0, 0, 0));
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/icons8-menu-rounded-50.png"))); // NOI18N
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });
        body.add(menu1);
        menu1.setBounds(150, 40, 40, 40);

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/vintageSCC.jpg"))); // NOI18N
        body.add(logo1);
        logo1.setBounds(0, 40, 200, 450);

        getContentPane().add(body);
        body.setBounds(0, 0, 980, 500);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(973, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboardMouseClicked
     adminDashPage dbp=new adminDashPage();
     mainDesktop.add(dbp).setVisible(true);
    }//GEN-LAST:event_nav_dashboardMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       close.setBackground(closecolor);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
         close.setBackground(headcolor);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void nav_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboardMouseEntered
      nav_dashboard.setBackground(lightcolor);
    }//GEN-LAST:event_nav_dashboardMouseEntered
    
    private void nav_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboardMouseExited
         nav_dashboard.setBackground(navcolor);
    }//GEN-LAST:event_nav_dashboardMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
            minimize.setBackground(mincolor);  
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
         minimize.setBackground(headcolor);  
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void nav_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_accountMouseClicked
     adminSet sp=new adminSet();
     mainDesktop.add(sp).setVisible(true);
    }//GEN-LAST:event_nav_accountMouseClicked

    private void nav_accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_accountMouseEntered
         nav_account.setBackground(lightcolor);
    }//GEN-LAST:event_nav_accountMouseEntered

    private void nav_accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_accountMouseExited
        nav_account.setBackground(navcolor);
    }//GEN-LAST:event_nav_accountMouseExited
    int x=200;
    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
       if (x==200){
           navbar.setSize(200,500);
           Thread th=new Thread(){
               @Override
               public void run(){
               
                   try{
                       for(int i=50;i>=0;i--){
                           Thread.sleep(i);
                           navbar.setSize(i,500);
                         
                       }
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
           };th.start();
           x=0;
           
       }
    }//GEN-LAST:event_menuMouseClicked

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        if (x==0){
            navbar.show();
           navbar.setSize(x,500);
           Thread th=new Thread(){
               @Override
               public void run(){
                   
                   try{
                       for(int i=180;i<=x;i++){
                           Thread.sleep(i);
                           navbar.setSize(i,500);
                        
                       }
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
           };th.start();
           x=200;
           
        }   
    }//GEN-LAST:event_menu1MouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        
    }//GEN-LAST:event_menuMouseEntered

    private void nav_student1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseClicked

    private void nav_student1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseEntered

    private void nav_student1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      applicants f=new applicants();
      f.setVisible(true);
      this.mainDesktop.add(f);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel accName1;
    public static javax.swing.JLabel accName2;
    private javax.swing.JPanel body;
    private javax.swing.JPanel close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu1;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel nav_account;
    private javax.swing.JPanel nav_dashboard;
    private javax.swing.JPanel nav_student1;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel navdesign;
    // End of variables declaration//GEN-END:variables
}
