/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminMain;

import LoginForm.LoginForm;
import adminInternalPage.adminDashPage;
import adminInternalPage.adminSet;
//import static adminMain..table;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class Admin extends javax.swing.JFrame {

    public static Object btn2;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
         nav_dashboard1.setVisible(true);
         jInternalFrame1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI b1=(BasicInternalFrameUI)jInternalFrame1.getUI();
        b1.setNorthPane(null);
         jInternalFrame2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI b2=(BasicInternalFrameUI)jInternalFrame2.getUI();
        b2.setNorthPane(null);
         jInternalFrame3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI b3=(BasicInternalFrameUI)jInternalFrame3.getUI();
        b3.setNorthPane(null);
    }
 Color navcolor=new Color(255,66,66);
    Color logcolor=new Color(51,51,255);
    Color navecolor=new Color(0,43,50);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(102,102,102);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    Color logincolor=new Color(0,43,50);
     Color whitecolor=new Color(255,255,255);
    Color graycolor=new Color(51,51,51);
    Color dgreencolor=new Color(27,102,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        nav_student1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nav_dashboard1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        manageApply = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        archieveData = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        viewStatus = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        viewApplicants = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        appHome = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        switchTab = new javax.swing.JTabbedPane();
        tabHome = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        tabForm = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        scc = new javax.swing.JLabel();
        personalData = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        postal = new javax.swing.JTextField();
        purok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        scholarLogo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        brgy = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Bdate = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        province = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        reset = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jCombo2 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        tabManage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        update = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        delete1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        s1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        s2 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        s3 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        backArrow = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        unifast = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        backArrow2 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        ched = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        backArrow3 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        tulongDunong = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        backArrow4 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        reset1 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        reset2 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        backArrow5 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav_student1.setBackground(new java.awt.Color(0, 43, 50));
        nav_student1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_student1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_student1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_student1MouseExited(evt);
            }
        });
        nav_student1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        nav_student1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 120));

        nav_dashboard1.setBackground(new java.awt.Color(255, 66, 66));
        nav_dashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_dashboard1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_dashboard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_dashboard1MouseExited(evt);
            }
        });
        nav_dashboard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-form-44.png"))); // NOI18N
        jLabel33.setText("APPLY ");
        nav_dashboard1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 50));

        nav_student1.add(nav_dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 50));

        manageApply.setBackground(new java.awt.Color(255, 66, 66));
        manageApply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageApplyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageApplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageApplyMouseExited(evt);
            }
        });
        manageApply.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-44.png"))); // NOI18N
        jLabel34.setText("MANAGE");
        manageApply.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        nav_student1.add(manageApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 50));

        logout.setBackground(new java.awt.Color(255, 66, 66));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(183, 30, 30));
        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-logout-44.png"))); // NOI18N
        jLabel9.setText("LOGOUT");
        logout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 50));

        nav_student1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, 50));

        archieveData.setBackground(new java.awt.Color(255, 66, 66));
        archieveData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archieveDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archieveDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archieveDataMouseExited(evt);
            }
        });
        archieveData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-delivery-44.png"))); // NOI18N
        jLabel50.setText("ARCHIEVE");
        archieveData.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        nav_student1.add(archieveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 200, 50));

        viewStatus.setBackground(new java.awt.Color(255, 66, 66));
        viewStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewStatusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewStatusMouseExited(evt);
            }
        });
        viewStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-delivery-44.png"))); // NOI18N
        jLabel55.setText("STATUS");
        viewStatus.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        jLabel43.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-delivery-44.png"))); // NOI18N
        jLabel43.setText("VIEW ALL");
        viewStatus.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        viewApplicants.setBackground(new java.awt.Color(255, 66, 66));
        viewApplicants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewApplicantsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewApplicantsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewApplicantsMouseExited(evt);
            }
        });
        viewApplicants.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        viewStatus.add(viewApplicants, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        nav_student1.add(viewStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 50));

        navbar.add(nav_student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 200, 670));

        jPanel9.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 590));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(255, 255, 255));
        minimize.setForeground(new java.awt.Color(255, 51, 51));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-subtract-26.png"))); // NOI18N
        minimize.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 40, 30));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setForeground(new java.awt.Color(255, 0, 0));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-close-26.png"))); // NOI18N
        close.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 30));

        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 60, 30));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        header1.setBackground(new java.awt.Color(255, 66, 66));
        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ScholarshipTracker- St.Cecilia's College-Cebu Inc. ");
        header1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 20));

        appHome.setBackground(new java.awt.Color(255, 66, 66));
        appHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appHomeMouseExited(evt);
            }
        });
        appHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/home.png"))); // NOI18N
        jLabel38.setText("  HOME");
        appHome.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 50));

        header1.add(appHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 140, 50));

        userName.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-user-54 (2).png"))); // NOI18N
        header1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 220, 50));

        jPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1090, 50));

        switchTab.setBackground(new java.awt.Color(255, 255, 204));

        tabHome.setLayout(null);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground1.jpg"))); // NOI18N
        tabHome.add(jLabel42);
        jLabel42.setBounds(180, 90, 540, 410);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/vintageSCC-1000.jpg"))); // NOI18N
        tabHome.add(jLabel41);
        jLabel41.setBounds(0, 0, 880, 590);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        tabHome.add(jLabel40);
        jLabel40.setBounds(0, 0, 910, 600);

        switchTab.addTab("tab3", tabHome);

        tabForm.setBackground(new java.awt.Color(255, 255, 255));
        tabForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        tabForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 500));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 1037));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scc.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        scc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scc.setText("ST.CECILIA'S COLLEGE-CEBU INC.");
        jPanel2.add(scc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 370, 30));

        personalData.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        personalData.setText("I. Personal Data");
        jPanel2.add(personalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 190, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Poblacion, Ward II, Minglanilla, Cebu, Philippines");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 310, -1));

        postal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 180, 30));

        purok.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        purok.setName(""); // NOI18N
        jPanel2.add(purok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 190, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Tell us about yourself");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, -1));

        scholarLogo.setBackground(new java.awt.Color(204, 204, 204));
        scholarLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        scholarLogo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, 90));

        jPanel2.add(scholarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 190, 110));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scclogo-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 210, 190));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Middle Name");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 90, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Ex: 10-03-2002");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, -1));

        MName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(MName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 200, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Last Name");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 90, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("Full Name ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 30));

        LName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 180, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("First Name");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 90, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Postal/Zip Code");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 740, 100, 20));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Birthdate");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 30));

        FName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 250, 30));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setText("Cell phone No.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 130, 30));

        number.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        number.setName(""); // NOI18N
        jPanel2.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 240, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Month-Day-Year");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 110, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setText("Email");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 100, 30));

        email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        email.setName(""); // NOI18N
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 270, 30));

        brgy.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        brgy.setName(""); // NOI18N
        jPanel2.add(brgy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 200, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Ex: Scc@gmail.com");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 130, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Barangay/Street Name");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 160, -1));

        Bdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 140, 30));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setText("Gender");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 790, 110, 30));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Purok / Sitio Name");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, 160, -1));

        gender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 790, 140, 30));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Write Male or Female");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 830, 150, -1));

        province.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(province, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 700, 210, 30));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("State/Province");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 740, 100, 20));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setText("Home Address");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 120, 30));

        city.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 210, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("City/Municipality");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 110, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 630, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 750, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 770, 630, 10));

        jScrollPane1.setViewportView(jPanel2);

        tabForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 820, 440));

        reset.setBackground(new java.awt.Color(0, 43, 80));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        reset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESET");
        reset.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 40));

        tabForm.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 120, -1));

        submit.setBackground(new java.awt.Color(255, 51, 51));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        submit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(255, 66, 66));
        jLabel36.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document_tracking_system/images/forward.png"))); // NOI18N
        jLabel36.setText("SUBMIT");
        submit.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        tabForm.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 130, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 0, 0));
        tabForm.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 482, 780, 10));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SCHOLARSHIP APPLICATION FORM");
        tabForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 370, 40));

        jCombo2.setBackground(new java.awt.Color(255, 0, 0));
        jCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCHOLARSHIPS", "UNIFAST", "CHED", "TULONG-DUNONG" }));
        jCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo2ActionPerformed(evt);
            }
        });
        tabForm.add(jCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 160, 40));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        tabForm.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
        tabForm.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 810, 10));

        switchTab.addTab("tab1", tabForm);

        tabManage.setBackground(new java.awt.Color(153, 153, 153));
        tabManage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Midle Name", "Last Name", "Birth Date", "Contact No.", "Email         ", "Address", "Gender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        tabManage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 750, 390));

        update.setBackground(new java.awt.Color(0, 43, 80));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("UPDATE");
        update.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 40));

        tabManage.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 90, 40));

        delete1.setBackground(new java.awt.Color(255, 66, 66));
        delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delete1MouseExited(evt);
            }
        });
        delete1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DELETE");
        delete1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 40));

        tabManage.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 90, 40));

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        tabManage.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, 30));

        jLabel5.setText("Search");
        tabManage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 30));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("MANAGE SCHOLARSHIP APPLICANTS");
        tabManage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 350, 30));
        tabManage.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 750, -1));
        tabManage.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 750, 10));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        tabManage.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        switchTab.addTab("tab2", tabManage);

        jPanel3.setLayout(null);

        s1.setBackground(new java.awt.Color(27, 102, 102));
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s1MouseExited(evt);
            }
        });
        s1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground3.jpg"))); // NOI18N
        s1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 120));

        jLabel44.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText(" UNIFAST APPLICANTS");
        s1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 30));

        jPanel3.add(s1);
        s1.setBounds(70, 190, 240, 170);

        s2.setBackground(new java.awt.Color(27, 102, 102));
        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s2MouseExited(evt);
            }
        });
        s2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground3.jpg"))); // NOI18N
        s2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 120));

        jLabel46.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("CHED APPLICANTS");
        s2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 150, 30));

        jPanel3.add(s2);
        s2.setBounds(340, 190, 240, 170);

        s3.setBackground(new java.awt.Color(27, 102, 102));
        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s3MouseExited(evt);
            }
        });
        s3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground3.jpg"))); // NOI18N
        s3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 120));

        jLabel48.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText(" TULONG-DUNONG APPLICANTS");
        s3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 220, 30));

        jPanel3.add(s3);
        s3.setBounds(610, 190, 220, 170);

        backArrow.setBackground(new java.awt.Color(204, 255, 204));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrowMouseExited(evt);
            }
        });
        backArrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setBackground(new java.awt.Color(0, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel3.add(backArrow);
        backArrow.setBounds(0, 0, 40, 30);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        jPanel3.add(jLabel49);
        jLabel49.setBounds(0, 0, 900, 600);

        switchTab.addTab("tab4", jPanel3);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        unifast.setBackground(new java.awt.Color(153, 153, 153));
        unifast.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Midle Name", "Last Name", "Birth Date", "Contact No.", "Email         ", "Address", "Gender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable5);

        unifast.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 750, 390));

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        unifast.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, 30));

        jLabel66.setText("Search");
        unifast.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 30));

        jLabel67.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel67.setText("UNIFAST SCHOLARSHIP APPLICANTS");
        unifast.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 350, 30));
        unifast.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 750, -1));
        unifast.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 750, 10));

        backArrow2.setBackground(new java.awt.Color(204, 255, 204));
        backArrow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrow2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrow2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrow2MouseExited(evt);
            }
        });
        backArrow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setBackground(new java.awt.Color(0, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        unifast.add(backArrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        unifast.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 900, 570));

        jInternalFrame1.getContentPane().add(unifast);
        unifast.setBounds(0, -3, 890, 570);

        switchTab.addTab("tab5", jInternalFrame1);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        ched.setBackground(new java.awt.Color(153, 153, 153));
        ched.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Midle Name", "Last Name", "Birth Date", "Contact No.", "Email         ", "Address", "Gender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable6);

        ched.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 750, 390));

        jTextField6.setBackground(new java.awt.Color(255, 255, 204));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ched.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 190, 30));

        jLabel71.setText("Search");
        ched.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 30));

        jLabel72.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel72.setText("CHED SCHOLARSHIP APPLICANTS");
        ched.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 350, 30));
        ched.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 750, -1));
        ched.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 750, 10));

        backArrow3.setBackground(new java.awt.Color(204, 255, 204));
        backArrow3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrow3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrow3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrow3MouseExited(evt);
            }
        });
        backArrow3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setBackground(new java.awt.Color(0, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        ched.add(backArrow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        ched.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        jInternalFrame2.getContentPane().add(ched);
        ched.setBounds(0, -3, 900, 570);

        switchTab.addTab("tab6", jInternalFrame2);

        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(null);

        tulongDunong.setBackground(new java.awt.Color(153, 153, 153));
        tulongDunong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Midle Name", "Last Name", "Birth Date", "Contact No.", "Email         ", "Address", "Gender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable7);

        tulongDunong.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 750, 390));

        jTextField7.setBackground(new java.awt.Color(255, 255, 204));
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        tulongDunong.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, 30));

        jLabel77.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel77.setText("TULONG-DUNONG SCHOLARSHIP APPLICANTS");
        tulongDunong.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 420, 30));
        tulongDunong.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 750, -1));
        tulongDunong.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 750, 10));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tulongDunong.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 30));

        backArrow4.setBackground(new java.awt.Color(204, 255, 204));
        backArrow4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrow4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrow4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrow4MouseExited(evt);
            }
        });
        backArrow4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setBackground(new java.awt.Color(0, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        tulongDunong.add(backArrow4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        tulongDunong.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        jInternalFrame3.getContentPane().add(tulongDunong);
        tulongDunong.setBounds(0, -3, 900, 570);

        switchTab.addTab("tab7", jInternalFrame3);

        jPanel4.setLayout(null);

        jLabel80.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel80.setText("DELETED SCHOLARSHIP APPLICANTS");
        jPanel4.add(jLabel80);
        jLabel80.setBounds(60, 20, 337, 24);

        reset1.setBackground(new java.awt.Color(0, 43, 80));
        reset1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reset1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reset1MouseExited(evt);
            }
        });
        reset1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("RESTORE");
        reset1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 40));

        jPanel4.add(reset1);
        reset1.setBounds(230, 520, 110, 40);

        reset2.setBackground(new java.awt.Color(255, 56, 56));
        reset2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reset2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reset2MouseExited(evt);
            }
        });
        reset2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("PERMANENTLY DELETE");
        reset2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 40));

        jPanel4.add(reset2);
        reset2.setBounds(460, 520, 220, 40);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Midle Name", "Last Name", "Birth Date", "Contact No.", "Email         ", "Address", "Gender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable8);

        jPanel4.add(jScrollPane9);
        jScrollPane9.setBounds(30, 60, 840, 420);

        backArrow5.setBackground(new java.awt.Color(204, 255, 204));
        backArrow5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrow5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrow5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrow5MouseExited(evt);
            }
        });
        backArrow5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setBackground(new java.awt.Color(0, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel4.add(backArrow5);
        backArrow5.setBounds(0, 0, 40, 30);

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/27565.png"))); // NOI18N
        jPanel4.add(jLabel76);
        jLabel76.setBounds(0, 0, 900, 600);

        switchTab.addTab("tab8", jPanel4);

        jPanel1.add(switchTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 880, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav_dashboard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboard1MouseExited
        nav_dashboard1.setBackground(headcolor);
    }//GEN-LAST:event_nav_dashboard1MouseExited

    private void nav_dashboard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboard1MouseEntered
       nav_dashboard1.setBackground(graycolor);
    }//GEN-LAST:event_nav_dashboard1MouseEntered

    private void nav_dashboard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboard1MouseClicked
        switchTab.setSelectedIndex(1);
    }//GEN-LAST:event_nav_dashboard1MouseClicked

    private void manageApplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageApplyMouseExited
         manageApply.setBackground(headcolor);
    }//GEN-LAST:event_manageApplyMouseExited

    private void manageApplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageApplyMouseEntered
        manageApply.setBackground(graycolor);
    }//GEN-LAST:event_manageApplyMouseEntered

    private void manageApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageApplyMouseClicked
        switchTab.setSelectedIndex(2);
    }//GEN-LAST:event_manageApplyMouseClicked

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(whitecolor);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(closecolor);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked
int x=1082;
    private void nav_student1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseExited

    private void nav_student1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseEntered

    private void nav_student1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseClicked

    private void delete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete1MouseEntered
         delete1.setBackground(mincolor);
    }//GEN-LAST:event_delete1MouseEntered

    private void delete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete1MouseExited
        delete1.setBackground(navecolor);
    }//GEN-LAST:event_delete1MouseExited

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
       
        String fn= FName.getText();
        String ln= LName.getText();
        String mn= MName.getText();
        String bd= Bdate.getText();
        String nb= number.getText();
        String em= email.getText();
        String by= brgy.getText();
        String pk= purok.getText();
        String cy= city.getText();
        String prov= province.getText();
        String pl= postal.getText();
        String gr= gender.getText();

   //     Admin si=new Admin();
       // si.setVisible(true);
        //this.dispose();
        if(fn.equals("")||ln.equals("")||mn.equals("")||bd.equals("")
            ||nb.equals("")||em.equals("")||by.equals("")||pk.equals("")
            ||cy.equals("")||prov.equals("")||pl.equals("")||gr.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter all the data!");

        }else{
            String data[]={FName.getText(),LName.getText(),MName.getText(),
                Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
            DefaultTableModel tbl= (DefaultTableModel)jTable1.getModel();
            tbl.addRow(data);

            JOptionPane.showMessageDialog(this,"Add data successfully...!");
         /*   FName.setText("");
            LName.setText("");
            MName.setText("");
            Bdate.setText("");
            number.setText("");
            email.setText("");
            brgy.setText("");
            purok.setText("");
            city.setText("");
            province.setText("");
            postal.setText("");
            gender.setText("");*/
        }
    }//GEN-LAST:event_submitMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        String fn= FName.getText();
        String ln= LName.getText();
        String mn= MName.getText();
        String bd= Bdate.getText();
        String nb= number.getText();
        String em= email.getText();
        String by= brgy.getText();
        String pk= purok.getText();
        String cy= city.getText();
        String prov= province.getText();
        String pl= postal.getText();
        String gr= gender.getText();

            JOptionPane.showMessageDialog(this,"ALL DATA HAS BEEN CLEARED...!");
            FName.setText("");
            LName.setText("");
            MName.setText("");
            Bdate.setText("");
            number.setText("");
            email.setText("");
            brgy.setText("");
            purok.setText("");
            city.setText("");
            province.setText("");
            postal.setText("");
            gender.setText("");
       
    }//GEN-LAST:event_resetMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
         update.setBackground(mincolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
         update.setBackground(navecolor);
    }//GEN-LAST:event_updateMouseExited

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(whitecolor);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(mincolor);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
      setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void appHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appHomeMouseClicked
        switchTab.setSelectedIndex(0);
    }//GEN-LAST:event_appHomeMouseClicked

    private void appHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appHomeMouseEntered
        appHome.setBackground(mincolor);
    }//GEN-LAST:event_appHomeMouseEntered

    private void appHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appHomeMouseExited
        appHome.setBackground(headcolor);
    }//GEN-LAST:event_appHomeMouseExited

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
             reset.setBackground(mincolor);

    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
            reset.setBackground(navecolor);
    }//GEN-LAST:event_resetMouseExited

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
         submit.setBackground(navecolor);
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
       submit.setBackground(headcolor);
    }//GEN-LAST:event_submitMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
     LoginForm main = new LoginForm();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(graycolor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(headcolor);
    }//GEN-LAST:event_logoutMouseExited

    private void viewApplicantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewApplicantsMouseClicked
       switchTab.setSelectedIndex(3);
    }//GEN-LAST:event_viewApplicantsMouseClicked

    private void viewApplicantsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewApplicantsMouseEntered
       viewApplicants.setBackground(graycolor);
    }//GEN-LAST:event_viewApplicantsMouseEntered

    private void viewApplicantsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewApplicantsMouseExited
         viewApplicants.setBackground(headcolor);
    }//GEN-LAST:event_viewApplicantsMouseExited

    private void s1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseClicked
           switchTab.setSelectedIndex(4);
    }//GEN-LAST:event_s1MouseClicked

    private void s1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseEntered
        s1.setBackground(lightcolor);
    }//GEN-LAST:event_s1MouseEntered

    private void s1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseExited
        s1.setBackground(dgreencolor);
    }//GEN-LAST:event_s1MouseExited

    private void s2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseClicked
switchTab.setSelectedIndex(5);
    }//GEN-LAST:event_s2MouseClicked

    private void s2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseEntered
        s2.setBackground(lightcolor);
    }//GEN-LAST:event_s2MouseEntered

    private void s2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseExited
        s2.setBackground(dgreencolor);
    }//GEN-LAST:event_s2MouseExited

    private void s3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseClicked
switchTab.setSelectedIndex(6);
    }//GEN-LAST:event_s3MouseClicked

    private void s3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseEntered
        s3.setBackground(lightcolor);
    }//GEN-LAST:event_s3MouseEntered

    private void s3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseExited
        s3.setBackground(dgreencolor);
    }//GEN-LAST:event_s3MouseExited

    private void jCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo2ActionPerformed
        if(jCombo2.getSelectedIndex()==1){
            String fn= FName.getText();
            String ln= LName.getText();
            String mn= MName.getText();
            String bd= Bdate.getText();
            String nb= number.getText();
            String em= email.getText();
            String by= brgy.getText();
            String pk= purok.getText();
            String cy= city.getText();
            String prov= province.getText();
            String pl= postal.getText();
            String gr= gender.getText();

            //     Admin si=new Admin();
            // si.setVisible(true);
            //this.dispose();
      
                String data[]={FName.getText(),LName.getText(),MName.getText(),
                    Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                    purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
                DefaultTableModel tbl= (DefaultTableModel)jTable5.getModel();
                tbl.addRow(data);

                JOptionPane.showMessageDialog(this,"Add data successfully...!");

        }if(jCombo2.getSelectedIndex()==2){
            String fn= FName.getText();
            String ln= LName.getText();
            String mn= MName.getText();
            String bd= Bdate.getText();
            String nb= number.getText();
            String em= email.getText();
            String by= brgy.getText();
            String pk= purok.getText();
            String cy= city.getText();
            String prov= province.getText();
            String pl= postal.getText();
            String gr= gender.getText();

            //     Admin si=new Admin();
            // si.setVisible(true);
            //this.dispose();
           
                String data[]={FName.getText(),LName.getText(),MName.getText(),
                    Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                    purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
                DefaultTableModel tbl= (DefaultTableModel)jTable6.getModel();
                tbl.addRow(data);

                JOptionPane.showMessageDialog(this,"Add data successfully...!");
              
            
        }if(jCombo2.getSelectedIndex()==3){
            String fn= FName.getText();
            String ln= LName.getText();
            String mn= MName.getText();
            String bd= Bdate.getText();
            String nb= number.getText();
            String em= email.getText();
            String by= brgy.getText();
            String pk= purok.getText();
            String cy= city.getText();
            String prov= province.getText();
            String pl= postal.getText();
            String gr= gender.getText();

            //     Admin si=new Admin();
            // si.setVisible(true);
            //this.dispose();
         
                String data[]={FName.getText(),LName.getText(),MName.getText(),
                    Bdate.getText(),number.getText(),email.getText(),brgy.getText(),
                    purok.getText(),city.getText(),province.getText(),postal.getText(),gender.getText()};
                DefaultTableModel tbl= (DefaultTableModel)jTable7.getModel();
                tbl.addRow(data);

                JOptionPane.showMessageDialog(this,"Add data successfully...!");
                
            
        }
    }//GEN-LAST:event_jCombo2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Search Button
        try{
            if( jTextField7.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Enter item!", "Oops Wait...!", JOptionPane.ERROR_MESSAGE);
            else{
                for( int r=0; r<100; r++)   //initializing row
                for( int c=0; c<4; c++) //initializing column
                jTable7.setValueAt("", r, c);

                BufferedReader rdfile= new BufferedReader( new FileReader("items.txt"));
                String[] line= new String[100];
                String search="", output="", target="";

                boolean same= false, found=false;

                int x=0, row=0;
                while( (line[x]= rdfile.readLine()) != null)//reading items.txt; asigning to array[] line
                x++;

                rdfile.close();

                search= jTextField7.getText();

                for( int k=0; line[k] != null; k++){
                    same= false;
                    target="";
                    for( int j=0; j < search.length(); j++)
                    target+= line[k].charAt(j);

                    if( search.equals(target))
                    same=true;

                    if( same){
                        String[] temp= line[k].split("\t");
                        jTable7.setValueAt((1000+k+1), row, 0);
                        for( int i=1; i<4; i++)
                        jTable7.setValueAt(temp[i-1], row,i);
                        row++;
                        found=true;
                    }
                }

                if( !found)
                JOptionPane.showMessageDialog(null, "Item(s) not found!", "Ooops!", JOptionPane.ERROR_MESSAGE);

                jTextField7.setText("");
            }
        }catch(IOException e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
         try{
            if( jTextField1.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Enter item!", "Ooops Wait...!", JOptionPane.ERROR_MESSAGE);
           
            else{
                BufferedReader rdfile= new BufferedReader( new FileReader("items.txt"));

                String[] itemline= new String[100];
                String temp[];
                String search= "", prod="";
                search= jTextField1.getText();
                boolean found= false;

                prod= jTextField1.getText();
                
                if( (!(prod.equals(""))) ){
                    while(( itemline[x]= rdfile.readLine()) != null){
                        temp= itemline[x].split("\t");

                        if( search.equals( temp[0])){
                            if( prod.equals(""))
                                prod= temp[0];
                           
                            itemline[x]= prod;
                            found= true;
                        }
                        x++;


                    }
                    rdfile.close();

                    if( found ){
                        PrintWriter wrfile= new PrintWriter( new FileWriter("items.txt"));

                        for( int j=0; itemline[j] != null; j++)
                            wrfile.println( itemline[j]);

                        wrfile.close();

                        JOptionPane.showMessageDialog(null, "Changes Saved!");
                    } else
                        JOptionPane.showMessageDialog(null, "Item Not Found!");

                    jTextField1.setText("");
                    jTextField1.setText("");
                 
                    
                    } else
                    JOptionPane.showMessageDialog( null, "No Changes Yet!");
            }
                
        }catch(IOException e){} catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Some input may be invalid!");
            
                    jTextField6.setText("");
               
        }
    
    }//GEN-LAST:event_updateMouseClicked

    private void archieveDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archieveDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_archieveDataMouseClicked

    private void archieveDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archieveDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_archieveDataMouseEntered

    private void archieveDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archieveDataMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_archieveDataMouseExited

    private void reset2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reset2MouseExited

    private void reset2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reset2MouseEntered

    private void reset2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reset2MouseClicked

    private void reset1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1MouseExited

    private void reset1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1MouseEntered

    private void reset1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1MouseClicked

    private void backArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseClicked
        this.toBack();
        adminDashBoard apd= new adminDashBoard();
        setVisible(false);
        new adminDashBoard().toFront();
        new adminDashBoard().setState(java.awt.Frame.NORMAL);
        apd.toFront();
    }//GEN-LAST:event_backArrowMouseClicked

    private void backArrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseEntered
        backArrow.setBackground(lightcolor);
    }//GEN-LAST:event_backArrowMouseEntered

    private void backArrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseExited
        backArrow.setBackground(backcolor);
    }//GEN-LAST:event_backArrowMouseExited

    private void backArrow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow2MouseClicked

    private void backArrow2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow2MouseEntered

    private void backArrow2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow2MouseExited

    private void backArrow3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow3MouseClicked

    private void backArrow3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow3MouseEntered

    private void backArrow3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow3MouseExited

    private void backArrow4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow4MouseClicked

    private void backArrow4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow4MouseEntered

    private void backArrow4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow4MouseExited

    private void backArrow5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow5MouseClicked

    private void backArrow5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow5MouseEntered

    private void backArrow5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backArrow5MouseExited

    private void viewStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStatusMouseClicked

    private void viewStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStatusMouseEntered

    private void viewStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewStatusMouseExited

public static void AddRowToJTable(Object[] dataRow){
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           model.addRow(dataRow);
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
     LoginForm log;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bdate;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField MName;
    private javax.swing.JPanel appHome;
    public static javax.swing.JPanel archieveData;
    private javax.swing.JPanel backArrow;
    private javax.swing.JPanel backArrow2;
    private javax.swing.JPanel backArrow3;
    private javax.swing.JPanel backArrow4;
    private javax.swing.JPanel backArrow5;
    private javax.swing.JTextField brgy;
    private javax.swing.JPanel ched;
    private javax.swing.JTextField city;
    private javax.swing.JPanel close;
    public static javax.swing.JPanel delete1;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gender;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombo2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable5;
    public static javax.swing.JTable jTable6;
    public static javax.swing.JTable jTable7;
    public static javax.swing.JTable jTable8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logout;
    public static javax.swing.JPanel manageApply;
    private javax.swing.JPanel minimize;
    public static javax.swing.JPanel nav_dashboard1;
    private javax.swing.JPanel nav_student1;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField number;
    private javax.swing.JLabel personalData;
    private javax.swing.JTextField postal;
    private javax.swing.JTextField province;
    private javax.swing.JTextField purok;
    public static javax.swing.JPanel reset;
    public static javax.swing.JPanel reset1;
    public static javax.swing.JPanel reset2;
    private javax.swing.JPanel s1;
    private javax.swing.JPanel s2;
    private javax.swing.JPanel s3;
    private javax.swing.JLabel scc;
    private javax.swing.JPanel scholarLogo;
    public static javax.swing.JPanel submit;
    private static javax.swing.JTabbedPane switchTab;
    private javax.swing.JPanel tabForm;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabManage;
    private javax.swing.JPanel tulongDunong;
    private javax.swing.JPanel unifast;
    public static javax.swing.JPanel update;
    public static javax.swing.JLabel userName;
    public static javax.swing.JPanel viewApplicants;
    public static javax.swing.JPanel viewStatus;
    // End of variables declaration//GEN-END:variables

    
}
