/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentsInternalPage;

import javax.swing.plaf.basic.BasicInternalFrameUI;

import java.awt.Color;
import static java.awt.Frame.ICONIFIED;
import adminMain.adminDashBoard;
/**
 *
 * @author Administrator
 */
public class studentPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form studentPage
     */
    public studentPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    Color navcolor=new Color(255,66,66);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(102,102,102);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    Color dgreencolor=new Color(27,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studBody = new javax.swing.JPanel();
        backArrow1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        s2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mini = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(656, 446));
        getContentPane().setLayout(null);

        studBody.setBackground(new java.awt.Color(255, 255, 204));
        studBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backArrow1.setBackground(new java.awt.Color(255, 66, 66));
        backArrow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrow1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrow1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrow1MouseExited(evt);
            }
        });
        backArrow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 66, 66));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        studBody.add(backArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        s1.setBackground(new java.awt.Color(27, 102, 102));
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s1MouseExited(evt);
            }
        });
        s1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground3.jpg"))); // NOI18N
        s1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 150));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" UNIFAST APPLICANTS");
        s1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 30));

        studBody.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, 200));

        s2.setBackground(new java.awt.Color(27, 102, 102));
        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s2MouseExited(evt);
            }
        });
        s2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground3.jpg"))); // NOI18N
        s2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 150));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CHED APPLICANTS");
        s2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, 30));

        studBody.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 240, 200));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLEASE SELECT ONE SCHOLARSHIP TO MANAGE STUDENTS APPLICANTION");
        studBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 500, 30));

        s3.setBackground(new java.awt.Color(27, 102, 102));
        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s3MouseExited(evt);
            }
        });
        s3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/scholarbackground3.jpg"))); // NOI18N
        s3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 150));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" TULONG-DUNONG APPLICANTS");
        s3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 30));

        studBody.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 240, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/Moss.jpg"))); // NOI18N
        studBody.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 250));

        header.setBackground(new java.awt.Color(255, 66, 66));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 66, 66));
        close.setForeground(new java.awt.Color(255, 0, 0));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-close-26.png"))); // NOI18N
        close.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 40));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 13, 13));
        jLabel4.setText("ScholarshipTracker- St.Cecilia's College-Cebu Inc. ");
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 300, 20));

        mini.setBackground(new java.awt.Color(255, 66, 66));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        mini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-subtract-26.png"))); // NOI18N
        mini.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, 40));

        studBody.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        getContentPane().add(studBody);
        studBody.setBounds(0, 0, 820, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backArrow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow1MouseClicked
    this.toBack();
        adminDashBoard apd= new adminDashBoard();
        setVisible(false);
        new adminDashBoard().toFront();
        new adminDashBoard().setState(java.awt.Frame.NORMAL);
        apd.toFront();
    }//GEN-LAST:event_backArrow1MouseClicked

    private void backArrow1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow1MouseEntered
      backArrow1.setBackground(lightcolor);
    }//GEN-LAST:event_backArrow1MouseEntered

    private void backArrow1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrow1MouseExited
      backArrow1.setBackground(backcolor);  
    }//GEN-LAST:event_backArrow1MouseExited

    private void s3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseEntered
         s3.setBackground(lightcolor);  
    }//GEN-LAST:event_s3MouseEntered

    private void s3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseExited
        s3.setBackground(dgreencolor);  
    }//GEN-LAST:event_s3MouseExited

    private void s1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseEntered
       s1.setBackground(lightcolor);
    }//GEN-LAST:event_s1MouseEntered

    private void s1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseExited
        s1.setBackground(dgreencolor);  
    }//GEN-LAST:event_s1MouseExited

    private void s2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseEntered
        s2.setBackground(lightcolor);
    }//GEN-LAST:event_s2MouseEntered

    private void s2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseExited
        s2.setBackground(dgreencolor);  
    }//GEN-LAST:event_s2MouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(closecolor);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(headcolor);
    }//GEN-LAST:event_closeMouseExited

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered
         mini.setBackground(mincolor);
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited
        mini.setBackground(headcolor);
    }//GEN-LAST:event_miniMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backArrow1;
    private javax.swing.JPanel close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mini;
    private javax.swing.JPanel s1;
    private javax.swing.JPanel s2;
    private javax.swing.JPanel s3;
    private javax.swing.JPanel studBody;
    // End of variables declaration//GEN-END:variables

    private void setState(int ICONIFIED) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
