/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentsInternalPage;

import adminInternalPage.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import scholarPage.selectScholar;
import adminMain.adminDashBoard;

/**
 *
 * @author Administrator
 */
public class studentDashPage extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form dashBoardPage
     */
    public studentDashPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    Color navcolor=new Color(255,66,66);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(255,255,204);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    Color dgreencolor=new Color(27,102,102);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dshBody = new javax.swing.JPanel();
        backArrow = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        viewScholar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        applyScholar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        viewStatus = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        dshBody.setBackground(new java.awt.Color(255, 255, 204));
        dshBody.setForeground(new java.awt.Color(204, 204, 204));
        dshBody.setPreferredSize(new java.awt.Dimension(750, 439));
        dshBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backArrow.setBackground(new java.awt.Color(255, 255, 204));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrowMouseExited(evt);
            }
        });
        backArrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        dshBody.add(backArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel9.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel9.setText("SCHOLARSHIP TRACKING APP");
        dshBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 360, 40));

        jLabel10.setText("A TRACKING SYSTEM TO MANAGE STUDENT SCHOLARHIP APPLICATION");
        dshBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 420, 20));

        jPanel1.setBackground(new java.awt.Color(0, 43, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 120));

        dshBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 170, 180));

        jPanel2.setBackground(new java.awt.Color(255, 66, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewScholar.setBackground(new java.awt.Color(255, 255, 204));
        viewScholar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewScholarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewScholarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewScholarMouseExited(evt);
            }
        });
        viewScholar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VIEW SCHOLARHIPS");
        viewScholar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-94.png"))); // NOI18N
        viewScholar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, 150, 120));

        jPanel2.add(viewScholar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, 150));

        applyScholar.setBackground(new java.awt.Color(255, 255, 204));
        applyScholar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyScholarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applyScholarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applyScholarMouseExited(evt);
            }
        });
        applyScholar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APPLY SCHOLARSHIPS");
        applyScholar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 190, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-form-94.png"))); // NOI18N
        applyScholar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 120));

        jPanel2.add(applyScholar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 190, 150));

        viewStatus.setBackground(new java.awt.Color(255, 255, 204));
        viewStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewStatusMouseExited(evt);
            }
        });
        viewStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VIEW SCHOLARHSIP STATUS");
        viewStatus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-view-delivery-94.png"))); // NOI18N
        viewStatus.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 110));

        jPanel2.add(viewStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 210, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dshBody, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dshBody, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backArrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseEntered
       backArrow.setBackground(lightcolor);
    }//GEN-LAST:event_backArrowMouseEntered

    private void backArrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseExited
       backArrow.setBackground(backcolor);  
    }//GEN-LAST:event_backArrowMouseExited

    private void backArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseClicked
       this.toBack();
        adminDashBoard apd= new adminDashBoard();
        setVisible(false);
        new adminDashBoard().toFront();
        new adminDashBoard().setState(java.awt.Frame.NORMAL);
        apd.toFront();

    }//GEN-LAST:event_backArrowMouseClicked

    private void viewScholarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewScholarMouseClicked
       selectScholar ss=new selectScholar();
       ss.setVisible(true);
       //this.dispose();
    }//GEN-LAST:event_viewScholarMouseClicked

    private void viewScholarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewScholarMouseEntered
        viewScholar.setBackground(lightcolor);
    }//GEN-LAST:event_viewScholarMouseEntered

    private void viewScholarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewScholarMouseExited
      viewScholar.setBackground(bodycolor);
    }//GEN-LAST:event_viewScholarMouseExited

    private void applyScholarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyScholarMouseEntered
         applyScholar.setBackground(lightcolor);
    }//GEN-LAST:event_applyScholarMouseEntered

    private void applyScholarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyScholarMouseExited
        applyScholar.setBackground(bodycolor);
    }//GEN-LAST:event_applyScholarMouseExited

    private void viewStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatusMouseEntered
        viewStatus.setBackground(lightcolor);
    }//GEN-LAST:event_viewStatusMouseEntered

    private void viewStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStatusMouseExited
        viewStatus.setBackground(bodycolor);
    }//GEN-LAST:event_viewStatusMouseExited

    private void applyScholarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyScholarMouseClicked
      form fu=new form ();
       fu.setVisible(true);
       
    }//GEN-LAST:event_applyScholarMouseClicked
int x=200;    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel applyScholar;
    private javax.swing.JPanel backArrow;
    private javax.swing.JPanel dshBody;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel viewScholar;
    private javax.swing.JPanel viewStatus;
    // End of variables declaration//GEN-END:variables
}
