/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentsInternalPage;

import StudentsMain.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import StudentsInternalPage.studentDashPage;
import StudentsInternalPage.studentSet;
import adminInternalPage.adminDashPage;
import adminInternalPage.adminSet;
import StudentsInternalPage.storeData;
import adminMain.adminDashBoard;

/**
 *
 * @author Admin
 */
public class viewApplicants extends javax.swing.JFrame {

    /**
     * Creates new form studentDashBoard
     */
    public viewApplicants() {
        initComponents();
    }
  Color navcolor=new Color(255,66,66);
    Color headcolor=new Color(255,66,66);
    Color bodycolor=new Color(102,102,102);
    Color closecolor=new Color(0,153,255);
    Color mincolor=new Color(197,67,67);
    Color backcolor= new Color(255,255,204);
    Color lightcolor=new Color(204,204,204);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accName1 = new javax.swing.JLabel();
        accName2 = new javax.swing.JLabel();
        mainDesktop1 = new javax.swing.JDesktopPane();
        menu1 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        navdesign = new javax.swing.JLabel();
        nav_student1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        navdesign1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tulongDunong = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ched = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        unifast = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backArrow = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        body.setBackground(new java.awt.Color(255, 255, 204));
        body.setPreferredSize(new java.awt.Dimension(800, 420));
        body.setLayout(null);

        navbar.setBackground(new java.awt.Color(0,43,80));
        navbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 43, 80), 2));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        navbar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 120));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/icons8-menu-rounded-50.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
        });
        navbar.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 40));

        jPanel4.setBackground(new java.awt.Color(255, 66, 66));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BACK");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 80, 30));

        navbar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, -1));

        body.add(navbar);
        navbar.setBounds(0, 40, 200, 430);

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logo-w-resize-removebg-preview.png"))); // NOI18N
        body.add(logo2);
        logo2.setBounds(0, 100, 200, 80);

        header.setBackground(new java.awt.Color(255, 66, 66));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setBackground(new java.awt.Color(255, 66, 66));
        minimize.setForeground(new java.awt.Color(255, 51, 51));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        minimize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-subtract-26.png"))); // NOI18N
        minimize.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 40));

        close.setBackground(new java.awt.Color(255, 66, 66));
        close.setForeground(new java.awt.Color(255, 0, 0));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-close-26.png"))); // NOI18N
        close.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 50, 40));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 13, 13));
        jLabel3.setText("ScholarshipTracker- St.Cecilia's College-Cebu Inc. ");
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 20));

        accName1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        accName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.add(accName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 20));

        accName2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        accName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.add(accName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 160, 20));

        body.add(header);
        header.setBounds(0, 0, 980, 40);

        mainDesktop1.setBackground(new java.awt.Color(255, 255, 204));
        mainDesktop1.setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout mainDesktop1Layout = new javax.swing.GroupLayout(mainDesktop1);
        mainDesktop1.setLayout(mainDesktop1Layout);
        mainDesktop1Layout.setHorizontalGroup(
            mainDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        mainDesktop1Layout.setVerticalGroup(
            mainDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        body.add(mainDesktop1);
        mainDesktop1.setBounds(230, 130, 710, 280);

        menu1.setBackground(new java.awt.Color(0, 0, 0));
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImagesFolder/icons8-menu-rounded-50.png"))); // NOI18N
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });
        body.add(menu1);
        menu1.setBounds(150, 40, 40, 40);

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/vintageSCC.jpg"))); // NOI18N
        body.add(logo1);
        logo1.setBounds(0, 140, 200, 450);

        navdesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/vintageSCC-1000.jpg"))); // NOI18N
        navdesign.setPreferredSize(new java.awt.Dimension(100, 100));
        body.add(navdesign);
        navdesign.setBounds(0, 40, 200, 550);

        nav_student1.setBackground(new java.awt.Color(0,43,80));
        nav_student1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_student1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nav_student1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nav_student1MouseExited(evt);
            }
        });
        nav_student1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADMIN");
        nav_student1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 90, 40));

        body.add(nav_student1);
        nav_student1.setBounds(0, 40, 200, 460);

        navdesign1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/vintageSCC-1000.jpg"))); // NOI18N
        navdesign1.setPreferredSize(new java.awt.Dimension(100, 100));
        body.add(navdesign1);
        navdesign1.setBounds(0, 30, 200, 460);

        jPanel1.setBackground(new java.awt.Color(0,43,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tulongDunong.setBackground(new java.awt.Color(0, 43, 80));
        tulongDunong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tulongDunong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tulongDunongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tulongDunongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tulongDunongMouseExited(evt);
            }
        });
        tulongDunong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TULONG-DUNONG");
        tulongDunong.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 130, 40));

        jPanel1.add(tulongDunong, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 200, -1));

        ched.setBackground(new java.awt.Color(0, 43, 80));
        ched.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ched.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chedMouseExited(evt);
            }
        });
        ched.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CHED");
        ched.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 40));

        jPanel1.add(ched, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 200, -1));

        unifast.setBackground(new java.awt.Color(0, 43, 80));
        unifast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        unifast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unifastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unifastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unifastMouseExited(evt);
            }
        });
        unifast.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("UNIFAST");
        unifast.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 40));

        jPanel1.add(unifast, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, -1));

        body.add(jPanel1);
        jPanel1.setBounds(200, 40, 780, 40);

        jPanel2.setBackground(new java.awt.Color(0, 43, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UPDATE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 30));

        body.add(jPanel2);
        jPanel2.setBounds(450, 420, 110, 30);

        jPanel3.setBackground(new java.awt.Color(255, 66, 66));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DELETE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 30));

        body.add(jPanel3);
        jPanel3.setBounds(590, 420, 100, 30);

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.add(jTextField1);
        jTextField1.setBounds(630, 90, 210, 30);

        jLabel1.setText("Search");
        body.add(jLabel1);
        jLabel1.setBounds(850, 96, 40, 20);

        backArrow.setBackground(new java.awt.Color(255, 255, 204));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backArrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backArrowMouseExited(evt);
            }
        });
        backArrow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-back-arrow-26.png"))); // NOI18N
        backArrow.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        body.add(backArrow);
        backArrow.setBounds(200, 80, 50, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int x=200;
    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(mincolor);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(headcolor);
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(closecolor);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(headcolor);
    }//GEN-LAST:event_closeMouseExited

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        if (x==0){
            navbar.show();
            navbar.setSize(x,500);
            Thread th=new Thread(){
                @Override
                public void run(){

                    try{
                        for(int i=180;i<=x;i++){
                            Thread.sleep(i);
                            navbar.setSize(i,500);

                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            };th.start();
            x=200;

        }
    }//GEN-LAST:event_menu1MouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        if (x==200){
            navbar.setSize(200,500);
            Thread th=new Thread(){
                @Override
                public void run(){

                    try{
                        for(int i=50;i>=0;i--){
                            Thread.sleep(i);
                            navbar.setSize(i,500);

                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            };th.start();
            x=0;

        }
    }//GEN-LAST:event_menuMouseClicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered

    }//GEN-LAST:event_menuMouseEntered

    private void nav_student1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseClicked

    private void nav_student1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseEntered

    private void nav_student1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_student1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_student1MouseExited

    private void tulongDunongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tulongDunongMouseClicked
         storeData si=new storeData();
         form f=new form();
          mainDesktop1.add(f).setVisible(true);
        mainDesktop1.add(si).setVisible(true);
    }//GEN-LAST:event_tulongDunongMouseClicked

    private void tulongDunongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tulongDunongMouseEntered
        tulongDunong.setBackground(lightcolor);
    }//GEN-LAST:event_tulongDunongMouseEntered

    private void tulongDunongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tulongDunongMouseExited
       tulongDunong.setBackground(navcolor);
    }//GEN-LAST:event_tulongDunongMouseExited

    private void unifastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unifastMouseClicked
        storeData si=new storeData();
        form f=new form();
          mainDesktop1.add(f).setVisible(true);
        mainDesktop1.add(si).setVisible(true);
    }//GEN-LAST:event_unifastMouseClicked

    private void unifastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unifastMouseEntered
       unifast.setBackground(lightcolor);
    }//GEN-LAST:event_unifastMouseEntered

    private void unifastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unifastMouseExited
        unifast.setBackground(navcolor);
    }//GEN-LAST:event_unifastMouseExited

    private void chedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chedMouseClicked
         storeData  si=new storeData();
         form f=new form();
          mainDesktop1.add(f).setVisible(true);
        mainDesktop1.add(si).setVisible(true);
    }//GEN-LAST:event_chedMouseClicked

    private void chedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chedMouseEntered
       ched.setBackground(lightcolor);
    }//GEN-LAST:event_chedMouseEntered

    private void chedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chedMouseExited
       ched.setBackground(navcolor);
    }//GEN-LAST:event_chedMouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        this.toBack();
        adminDashBoard apd= new adminDashBoard();
        setVisible(true);
        new adminDashBoard().toFront();
        new adminDashBoard().setState(java.awt.Frame.NORMAL);
        apd.toFront();

    }//GEN-LAST:event_jPanel4MouseClicked

    private void backArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseClicked
        this.toBack();
        adminDashBoard apd= new adminDashBoard();
        setVisible(false);
        new adminDashBoard().toFront();
        new adminDashBoard().setState(java.awt.Frame.NORMAL);
        apd.toFront();
    }//GEN-LAST:event_backArrowMouseClicked

    private void backArrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseEntered
        backArrow.setBackground(lightcolor);
    }//GEN-LAST:event_backArrowMouseEntered

    private void backArrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMouseExited
        backArrow.setBackground(backcolor);
    }//GEN-LAST:event_backArrowMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewApplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewApplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewApplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewApplicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewApplicants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel accName1;
    public static javax.swing.JLabel accName2;
    private javax.swing.JPanel backArrow;
    private javax.swing.JPanel body;
    private javax.swing.JPanel ched;
    private javax.swing.JPanel close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JDesktopPane mainDesktop1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu1;
    private javax.swing.JPanel minimize;
    private javax.swing.JPanel nav_student1;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel navdesign;
    private javax.swing.JLabel navdesign1;
    private javax.swing.JPanel tulongDunong;
    private javax.swing.JPanel unifast;
    // End of variables declaration//GEN-END:variables
}
